### ISSUE TITLE
如何利用训练好的bert模型处理句对相似度的任务

### ISSUE THREAD

**Issue by KunWangR** [xmxoxo/BERT-train2deploy#14]
fine tune的时候是句对数据(text_a,text_b,label)，如何用Bert_base预测两个句子的相似度？bert_client的输入是什么？

**Comment by qiunian711** [comment]
> fine tune的时候是句对数据(text_a,text_b,label)，如何用Bert_base预测两个句子的相似度？bert_client的输入是什么？

您好，不知道您这个问题有没有解决，其实bert-as-server应该是可以解决这个问题的，因为他可以输出一段文字的feature，然后你可以自己再加一个相似性计算的处理，那就可以完成你上面说的功能了

**Comment by KunWangR** [comment]
我看过了代码，其实text_a和text_b通过“ ||| ”拼成一个文本输入bert_base，当作一个分类任务来微调训练，所以预测的时候，两个句子也这样拼接输入，就可以得到二分类的相似性了。
