### ISSUE TITLE
freeze_graph.py的问题2

### ISSUE THREAD

**Issue by lotest** [xmxoxo/BERT-train2deploy#15]
195行的latest_checkpoint = tf.train.latest_checkpoint(args.model_dir)
参数应该是 args.bert_model_dir

**Comment by fathouse** [comment]
你不要乱讲啊，明明是对的

**Comment by lotest** [comment]
是么，我不知道哪里的问题。改了之后才能跑

**Comment by fathouse** [comment]
这个是classification_model.pb的生成路径，改了这个，如果不进行其他相应的修改，生成的时候会找不到存储路径

**Comment by lotest** [comment]
对，是需要指定训练得到的模型文件的路径
