### ISSUE TITLE
模型服务端部署完成之后，通过调用端口进行测试，发现项目下面生成了很多tmp文件夹，有什么方法不生成吗

### ISSUE THREAD

**Issue by knavezl** [xmxoxo/BERT-train2deploy#26]

**Comment by xmxoxo** [comment]
这些临时文件是服务端启动时自动生成的，暂时没办法去掉不生成。
我用了一个简单的方式来处理： 每次启动服务时先删除旧的临时目录。

在bash脚本启动任务前先执行以下语句：

`echo 'start BERT mobile svr...'
cd /mnt/sda1/transdat/bert-demo/bert/mobile_svr
sudo rm -rf tmp*
`
完整的启动脚本叫  bertsvr.sh  我放到git根目录。

**Comment by knavezl** [comment]
感谢
