### ISSUE TITLE
端口测试的post body中的 id 111是从哪来的？

### ISSUE THREAD

**Issue by sunweiconfidence** [xmxoxo/BERT-train2deploy#6]
curl -X POST http://192.168.15.111:8091/encode \
  -H 'content-type: application/json' \
  -d '{"id": 111,"texts": ["总的来说，这款手机性价比是特别高的。","槽糕的售后服务！！！店大欺客"], "is_tokenized": false}'

请问您端口测试的id 111是从哪得来的？不太明白，谢谢。

**Comment by xmxoxo** [comment]
随意指定的，可用于识别返回的数据；

**Comment by sunweiconfidence** [comment]
好的，谢谢
